name: monads
description: A little fp style into dart. Easily for using, reading and contributing.
version: 0.0.1
homepage: https://github.com/fpdart/monads
author: FPDart Team <shindakioku@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
